controllers/MeterController.php
<?php

namespace app\controllers;

use app\components\EkmSummaryApi;
use Yii;
use app\models\Meter;
use app\models\MeterSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * MeterController implements the CRUD actions for Meter model.
 */
class MeterController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    ['allow' => true, 'roles' => ['@']]
                ]
            ]
        ];
    }

    /**
     * Lists all Meter models.
     * @return mixed
     */
    public function actionIndex()
    {
        $queryParams = Yii::$app->request->queryParams;
        $searchModel = new MeterSearch();
        $dataProvider = $searchModel->search($queryParams);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Meter model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        Yii::$app->ekmSummary->setReport(EkmSummaryApi::REPORT_HOUR);
        Yii::$app->ekmSummary->setMeters($model->id);
        $data = Yii::$app->ekmSummary->getData();
        $groupError = false;
        if (isset($data->error_code)) {
            $groupError = true;
        }
        return $this->render('view', [
            'model' => $model,
            'groupError' => $groupError
        ]);
    }

    /**
     * Creates a new Meter model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Meter();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Meter model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Meter model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Meter model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Meter the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Meter::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/MeterSummaryController.php
<?php

namespace app\controllers;

use Yii;
use app\models\MeterSummary;
use app\models\MeterSummarySearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * MeterSummaryController implements the CRUD actions for MeterSummary model.
 */
class MeterSummaryController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    ['allow' => true, 'roles' => ['@']]
                ]
            ]
        ];
    }

    /**
     * Lists all MeterSummary models.
     * @return mixed
     */
    public function actionIndex()
    {
        $queryParams = Yii::$app->request->queryParams;
        $prevParams = $queryParams;
        $nextParams = $queryParams;
        $searchModel = new MeterSummarySearch();
        $dataProvider = $searchModel->search($queryParams);
        $meter = $searchModel->meter;
        $title_prefix = '';
        $date_format = '';
        $chart_title = 'KWh Total Difference';
        switch ($queryParams['MeterSummarySearch']['report']) {
            case 'hr':
                $title_prefix = 'Hourly ';
                $date_format = 'h:i A';
                $prevParams['MeterSummarySearch']['max_start_timestamp'] = $queryParams['MeterSummarySearch']['min_start_timestamp'] - 1;
                $prevParams['MeterSummarySearch']['min_start_timestamp'] = strtotime('yesterday', $queryParams['MeterSummarySearch']['min_start_timestamp']);
                $nextParams['MeterSummarySearch']['min_start_timestamp'] = $queryParams['MeterSummarySearch']['max_start_timestamp'] + 1;
                $nextParams['MeterSummarySearch']['max_start_timestamp'] = strtotime('+1 day', $queryParams['MeterSummarySearch']['max_start_timestamp']);
                $dataProvider->setPagination(['pageSize' => 24]);
                break;
            case 'dy':
                $title_prefix = 'Daily ';
                $date_format = 'M d, Y';
                $prevParams['MeterSummarySearch']['min_start_timestamp'] = strtotime('first day of previous month',$queryParams['MeterSummarySearch']['min_start_timestamp']);
                $prevParams['MeterSummarySearch']['max_start_timestamp'] = strtotime('last day of previous month',$queryParams['MeterSummarySearch']['min_start_timestamp']) + (24 * 60 * 60) - 1;
                $nextParams['MeterSummarySearch']['min_start_timestamp'] = strtotime('first day of next month',$queryParams['MeterSummarySearch']['min_start_timestamp']);
                $nextParams['MeterSummarySearch']['max_start_timestamp'] = strtotime('last day of next month',$queryParams['MeterSummarySearch']['min_start_timestamp']) + (24 * 60 * 60) - 1;
                $dataProvider->setPagination(['pageSize' => 31]);
                break;
            case 'wk':
                $title_prefix = 'Weekly ';
                $date_format = 'M d, Y';
                $prevParams['MeterSummarySearch']['min_start_timestamp'] = strtotime(date('Y', $queryParams['MeterSummarySearch']['min_start_timestamp']) - 1 . '-01-01T00:00:00+08:00');
                $prevParams['MeterSummarySearch']['max_start_timestamp'] = strtotime(date('Y', $queryParams['MeterSummarySearch']['min_start_timestamp']) - 1 . '-12-31T11:59:59+08:00');
                $nextParams['MeterSummarySearch']['min_start_timestamp'] = strtotime(date('Y', $queryParams['MeterSummarySearch']['min_start_timestamp']) + 1 . '-01-01T00:00:00+08:00');
                $nextParams['MeterSummarySearch']['max_start_timestamp'] = strtotime(date('Y', $queryParams['MeterSummarySearch']['min_start_timestamp']) + 1 . '-12-31T11:59:59+08:00');
                $dataProvider->setPagination(['pageSize' => 100]);
                break;
            case 'mo':
                $title_prefix = 'Monthly ';
                $date_format = 'M Y';
                $prevParams['MeterSummarySearch']['min_start_timestamp'] = strtotime(date('Y', $queryParams['MeterSummarySearch']['min_start_timestamp']) - 1 . '-01-01T00:00:00+08:00');
                $prevParams['MeterSummarySearch']['max_start_timestamp'] = strtotime(date('Y', $queryParams['MeterSummarySearch']['min_start_timestamp']) - 1 . '-12-31T11:59:59+08:00');
                $nextParams['MeterSummarySearch']['min_start_timestamp'] = strtotime(date('Y', $queryParams['MeterSummarySearch']['min_start_timestamp']) + 1 . '-01-01T00:00:00+08:00');
                $nextParams['MeterSummarySearch']['max_start_timestamp'] = strtotime(date('Y', $queryParams['MeterSummarySearch']['min_start_timestamp']) + 1 . '-12-31T11:59:59+08:00');
                $dataProvider->setPagination(['pageSize' => 12]);
                break;
        }

        $chartLabels = [];
        $kwhTotDiffs = [];
        foreach($dataProvider->getModels() as $summary) {
            /* @var $summary \app\models\MeterSummary */
            $chartLabels[] = date($date_format, $summary->start_timestamp);
            $kwhTotDiffs[] = $summary->kWh_Tot_Diff;
        }

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'title_prefix' => $title_prefix,
            'meter' => $meter,
            'chartLabels' => $chartLabels,
            'kwhTotDiffs' => $kwhTotDiffs,
            'chart_title' => $chart_title,
            'prevParams' => $prevParams,
            'nextParams' => $nextParams,
            'queryParams' => $queryParams
        ]);
    }

    /**
     * Displays a single MeterSummary model.
     * @param integer $meter_id
     * @param string $report
     * @param string $start_timestamp
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($meter_id, $report, $start_timestamp)
    {
        return $this->render('view', [
            'model' => $this->findModel($meter_id, $report, $start_timestamp),
        ]);
    }

    /**
     * Creates a new MeterSummary model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @param string $override
     * @return mixed
     * @throws NotFoundHttpException if override string is not provided.
     */
    public function actionCreate($override)
    {
        if ('m3t3r' != $override) {
            throw new NotFoundHttpException('Error deleting summary.');
        }
        $model = new MeterSummary();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'meter_id' => $model->meter_id, 'report' => $model->report, 'start_timestamp' => $model->start_timestamp]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing MeterSummary model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $override
     * @param integer $meter_id
     * @param string $report
     * @param string $start_timestamp
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($override, $meter_id, $report, $start_timestamp)
    {
        if ('m3t3r' != $override) {
            throw new NotFoundHttpException('Error deleting summary.');
        }
        $model = $this->findModel($meter_id, $report, $start_timestamp);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'meter_id' => $model->meter_id, 'report' => $model->report, 'start_timestamp' => $model->start_timestamp]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing MeterSummary model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $override
     * @param integer $meter_id
     * @param string $report
     * @param string $start_timestamp
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($override, $meter_id, $report, $start_timestamp)
    {
        if ('m3t3r' != $override) {
            throw new NotFoundHttpException('Error deleting summary.');
        }
        $this->findModel($meter_id, $report, $start_timestamp)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the MeterSummary model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $meter_id
     * @param string $report
     * @param string $start_timestamp
     * @return MeterSummary the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($meter_id, $report, $start_timestamp)
    {
        if (($model = MeterSummary::findOne(['meter_id' => $meter_id, 'report' => $report, 'start_timestamp' => $start_timestamp])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/meter-summary/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\MeterSummary */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="meter-summary-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'meter_id')->textInput() ?>

    <?= $form->field($model, 'report')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'start_timestamp')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'end_timestamp')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'kWh_Tot_Min')->textInput() ?>

    <?= $form->field($model, 'kWh_Tot_Max')->textInput() ?>

    <?= $form->field($model, 'kWh_Tot_Diff')->textInput() ?>

    <?= $form->field($model, 'kWh_Tariff_1_Min')->textInput() ?>

    <?= $form->field($model, 'kWh_Tariff_1_Max')->textInput() ?>

    <?= $form->field($model, 'kWh_Tariff_1_Diff')->textInput() ?>

    <?= $form->field($model, 'kWh_Tariff_2_Min')->textInput() ?>

    <?= $form->field($model, 'kWh_Tariff_2_Max')->textInput() ?>

    <?= $form->field($model, 'kWh_Tariff_2_Diff')->textInput() ?>

    <?= $form->field($model, 'kWh_Tariff_3_Min')->textInput() ?>

    <?= $form->field($model, 'kWh_Tariff_3_Max')->textInput() ?>

    <?= $form->field($model, 'kWh_Tariff_3_Diff')->textInput() ?>

    <?= $form->field($model, 'kWh_Tariff_4_Min')->textInput() ?>

    <?= $form->field($model, 'kWh_Tariff_4_Max')->textInput() ?>

    <?= $form->field($model, 'kWh_Tariff_4_Diff')->textInput() ?>

    <?= $form->field($model, 'RMS_Volts_Ln_1_Average')->textInput() ?>

    <?= $form->field($model, 'RMS_Volts_Ln_1_StdDev')->textInput() ?>

    <?= $form->field($model, 'RMS_Volts_Ln_1_Min')->textInput() ?>

    <?= $form->field($model, 'RMS_Volts_Ln_1_Max')->textInput() ?>

    <?= $form->field($model, 'RMS_Volts_Ln_2_Average')->textInput() ?>

    <?= $form->field($model, 'RMS_Volts_Ln_2_StdDev')->textInput() ?>

    <?= $form->field($model, 'RMS_Volts_Ln_2_Min')->textInput() ?>

    <?= $form->field($model, 'RMS_Volts_Ln_2_Max')->textInput() ?>

    <?= $form->field($model, 'RMS_Volts_Ln_3_Average')->textInput() ?>

    <?= $form->field($model, 'RMS_Volts_Ln_3_StdDev')->textInput() ?>

    <?= $form->field($model, 'RMS_Volts_Ln_3_Min')->textInput() ?>

    <?= $form->field($model, 'RMS_Volts_Ln_3_Max')->textInput() ?>

    <?= $form->field($model, 'Amps_Ln_1_Average')->textInput() ?>

    <?= $form->field($model, 'Amps_Ln_1_StdDev')->textInput() ?>

    <?= $form->field($model, 'Amps_Ln_1_Min')->textInput() ?>

    <?= $form->field($model, 'Amps_Ln_1_Max')->textInput() ?>

    <?= $form->field($model, 'Amps_Ln_2_Average')->textInput() ?>

    <?= $form->field($model, 'Amps_Ln_2_StdDev')->textInput() ?>

    <?= $form->field($model, 'Amps_Ln_2_Min')->textInput() ?>

    <?= $form->field($model, 'Amps_Ln_2_Max')->textInput() ?>

    <?= $form->field($model, 'Amps_Ln_3_Average')->textInput() ?>

    <?= $form->field($model, 'Amps_Ln_3_StdDev')->textInput() ?>

    <?= $form->field($model, 'Amps_Ln_3_Min')->textInput() ?>

    <?= $form->field($model, 'Amps_Ln_3_Max')->textInput() ?>

    <?= $form->field($model, 'RMS_Watts_Ln_1_Average')->textInput() ?>

    <?= $form->field($model, 'RMS_Watts_Ln_1_StdDev')->textInput() ?>

    <?= $form->field($model, 'RMS_Watts_Ln_1_Min')->textInput() ?>

    <?= $form->field($model, 'RMS_Watts_Ln_1_Max')->textInput() ?>

    <?= $form->field($model, 'RMS_Watts_Ln_2_Average')->textInput() ?>

    <?= $form->field($model, 'RMS_Watts_Ln_2_StdDev')->textInput() ?>

    <?= $form->field($model, 'RMS_Watts_Ln_2_Min')->textInput() ?>

    <?= $form->field($model, 'RMS_Watts_Ln_2_Max')->textInput() ?>

    <?= $form->field($model, 'RMS_Watts_Ln_3_Average')->textInput() ?>

    <?= $form->field($model, 'RMS_Watts_Ln_3_StdDev')->textInput() ?>

    <?= $form->field($model, 'RMS_Watts_Ln_3_Min')->textInput() ?>

    <?= $form->field($model, 'RMS_Watts_Ln_3_Max')->textInput() ?>

    <?= $form->field($model, 'start_date')->textInput() ?>

    <?= $form->field($model, 'end_date')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/meter-summary/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\MeterSummary */

$this->title = 'Create Meter Summary';
$this->params['breadcrumbs'][] = ['label' => 'Meter Summaries', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="meter-summary-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/meter-summary/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\DetailView;
use dosamigos\chartjs\ChartJs;

/* @var $this yii\web\View */
/* @var $searchModel app\models\MeterSummarySearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $title_prefix string */

$this->title = $title_prefix . 'Meter Summaries';
$this->params['breadcrumbs'][] = ['label' => 'Meter', 'url' => ['meter/index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="meter-summary-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php
    try {
        echo DetailView::widget([
            'model' => $meter,
            'attributes' => [
                'id',
                'name',
                'description',
                [
                    'label' => 'Date Range',
                    'format' => 'html',
                    'value' => date('M d, Y h:i A', $queryParams['MeterSummarySearch']['min_start_timestamp']) . ' - ' . date('M d, Y h:i A', $queryParams['MeterSummarySearch']['max_start_timestamp'])
                ]
            ],
        ]);
    } catch (Exception $e) {
        echo '';
    }
    ?>
    <?php
    try {
        echo ChartJs::widget([
            'type' => 'line',
            'options' => [
                'height' => 100,
            ],
            'data' => [
                'labels' => $chartLabels,
                'datasets' => [
                    [
                        'label' => $chart_title,
                        'fill' => false,
                        'backgroundColor' => "rgba(179,181,198,0.2)",
                        'borderColor' => "rgba(179,181,198,1)",
                        'pointBackgroundColor' => "rgba(179,181,198,1)",
                        'pointBorderColor' => "#fff",
                        'pointHoverBackgroundColor' => "#fff",
                        'pointHoverBorderColor' => "rgba(179,181,198,1)",
                        'data' => $kwhTotDiffs
                    ]
                ]
            ]
        ]);
    } catch (Exception $e) {
        echo '';
    }
    ?>
    <?php
    try {
        echo GridView::widget([
            'dataProvider' => $dataProvider,
            //'filterModel' => $searchModel,
            'columns' => [
                'start_timestamp:datetime',
                'end_timestamp:datetime',
                'kWh_Tot_Min',
                'kWh_Tot_Max',
                'kWh_Tot_Diff',
                //'kWh_Tariff_1_Min',
                //'kWh_Tariff_1_Max',
                //'kWh_Tariff_1_Diff',
                //'kWh_Tariff_2_Min',
                //'kWh_Tariff_2_Max',
                //'kWh_Tariff_2_Diff',
                //'kWh_Tariff_3_Min',
                //'kWh_Tariff_3_Max',
                //'kWh_Tariff_3_Diff',
                //'kWh_Tariff_4_Min',
                //'kWh_Tariff_4_Max',
                //'kWh_Tariff_4_Diff',
                //'RMS_Volts_Ln_1_Average',
                //'RMS_Volts_Ln_1_StdDev',
                //'RMS_Volts_Ln_1_Min',
                //'RMS_Volts_Ln_1_Max',
                //'RMS_Volts_Ln_2_Average',
                //'RMS_Volts_Ln_2_StdDev',
                //'RMS_Volts_Ln_2_Min',
                //'RMS_Volts_Ln_2_Max',
                //'RMS_Volts_Ln_3_Average',
                //'RMS_Volts_Ln_3_StdDev',
                //'RMS_Volts_Ln_3_Min',
                //'RMS_Volts_Ln_3_Max',
                //'Amps_Ln_1_Average',
                //'Amps_Ln_1_StdDev',
                //'Amps_Ln_1_Min',
                //'Amps_Ln_1_Max',
                //'Amps_Ln_2_Average',
                //'Amps_Ln_2_StdDev',
                //'Amps_Ln_2_Min',
                //'Amps_Ln_2_Max',
                //'Amps_Ln_3_Average',
                //'Amps_Ln_3_StdDev',
                //'Amps_Ln_3_Min',
                //'Amps_Ln_3_Max',
                //'RMS_Watts_Ln_1_Average',
                //'RMS_Watts_Ln_1_StdDev',
                //'RMS_Watts_Ln_1_Min',
                //'RMS_Watts_Ln_1_Max',
                //'RMS_Watts_Ln_2_Average',
                //'RMS_Watts_Ln_2_StdDev',
                //'RMS_Watts_Ln_2_Min',
                //'RMS_Watts_Ln_2_Max',
                //'RMS_Watts_Ln_3_Average',
                //'RMS_Watts_Ln_3_StdDev',
                //'RMS_Watts_Ln_3_Min',
                //'RMS_Watts_Ln_3_Max',
                //'start_date',
                //'end_date',
            ],
        ]);
    } catch (Exception $e) {
        echo 'An error occurred while retrieving meter summary.';
    }
    ?>
    <div class="row">
        <div class="col-lg-6">
            <?= Html::a('Previous (' . date('M d, Y h:i A', $prevParams['MeterSummarySearch']['min_start_timestamp']) . ' - ' . date('M d, Y h:i A', $prevParams['MeterSummarySearch']['max_start_timestamp']) . ')', ['meter-summary/index'] + $prevParams, ['class' => 'btn btn-primary']); ?>
        </div>
        <div class="col-lg-6 col-sm-push-2">
            <?= Html::a('Next (' . date('M d, Y h:i A', $nextParams['MeterSummarySearch']['min_start_timestamp']) . ' - ' . date('M d, Y h:i A', $nextParams['MeterSummarySearch']['max_start_timestamp']) . ')', ['meter-summary/index'] + $nextParams, ['class' => 'btn btn-primary']); ?>
        </div>
    </div>
</div>

views/meter-summary/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\MeterSummary */

$this->title = 'Update Meter Summary: ' . $model->meter_id;
$this->params['breadcrumbs'][] = ['label' => 'Meter Summaries', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->meter_id, 'url' => ['view', 'meter_id' => $model->meter_id, 'report' => $model->report, 'start_timestamp' => $model->start_timestamp]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="meter-summary-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>