controllers/ReportController.php
<?php
/**
 * Created by PhpStorm.
 * User: joey
 * Date: 26/06/2019
 * Time: 9:29 AM
 */

namespace app\controllers;


use app\models\GroupsSearch;
use app\models\MeterSearch;
use app\models\Variables;
use yii\db\Query;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;

class ReportController extends Controller
{
    const GRANULARITY_METER = 'meter';
    const GRANULARITY_GROUP = 'groups';
    public $queryCount = 0;
    private $emissionFactor = null;

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    ['allow' => true, 'roles' => ['@']]
                ]
            ]
        ];
    }

    public static function getHtmlClass($data, $value, $min, $max)
    {
        $class = ['meter-data'];
        $values = [];
        foreach ($data as $tmp) {
            $values[] = $tmp['value'];
        }
        if (min($values) == $value) {
            $class[] = 'meter-data-row-min';
        }

        if (max($values) == $value) {
            $class[] = 'meter-data-row-max';
        }

        if ($min == $value) {
            $class[] = 'meter-data-min';
        }

        if ($max == $value) {
            $class[] = 'meter-data-max';
        }

        return implode(' ', $class);
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionMeter()
    {
        return $this->renderReport(self::GRANULARITY_METER);
    }

    public function actionGroups()
    {
        return $this->renderReport(self::GRANULARITY_GROUP);
    }

    public function renderReport($granularity)
    {
        $dropDownItems = [];
        switch ($granularity) {
            case self::GRANULARITY_METER:
                $dropDownItems = MeterSearch::find()->orderBy('name')->all();
                break;
            case self::GRANULARITY_GROUP:
                $dropDownItems = GroupsSearch::find()->orderBy('name')->all();
                break;
        }
        $data = [];
        if (\Yii::$app->request->get('id')) {
            $get = \Yii::$app->request->get();
            foreach ($get['id'] as $i => $value) {
                $result = $this->getQueryByGranularity($granularity, $get, $i)->all();
                $this->processResultsToData($get['type'], $get['data'], $get['color'], $result, $data, 'yes' == $get['shift']);
            }
            $this->postProcessData($data, 'yes' == $get['shift']);
        }
        if (strtoupper(\Yii::$app->request->get('submit')) == 'DOWNLOAD DATA') {
            header("Content-type: text/csv");
            header("Content-Disposition: attachment; filename=" . uniqid() . ".csv");
            header("Pragma: no-cache");
            header("Expires: 0");
            $csv = fopen("php://output", "w");
            $labels = ['yes' == $get['shift'] ? 'Date/Time' : '#'];
            foreach ($data['rows']['labels'] as $label) {
                if ('no' == $get['shift']) {
                    $labels[] = 'Date/Time';
                }
                $labels[] = $label;
            }
            fputcsv($csv, $labels);

            foreach ($data['labels'] as $index => $label) {
                $row = [];
                foreach ($data['rows']['data'][$index] as $item) {
                    if ('no' == $get['shift']) {
                        $row[] = $item['label'];
                    }
                    $row[] = $item['value'];
                }
                fputcsv($csv, array_merge([$label], $row));
            }
            fclose($csv);
            exit;
        }
        return $this->render('report',[
            'dropDownItems' => $dropDownItems,
            'granularity' => $granularity,
            'data' => $data
        ]);
    }

    public function postProcessData(&$data, $shift = true) {
        ksort($data['labels']);
        $data['rows'] = [
            'labels' => [],
            'data' => [],
        ];
        $data['min'] = null;
        $data['max'] = 0;
        foreach ($data['labels'] as $index => $label) {
            foreach ($data['data'] as $name => $value) {
                if ($shift && !isset($data['data'][$name][$index])) {
                    $data['data'][$name][$index]['label'] = $label;
                    $data['data'][$name][$index]['value'] = 0;
                }
                $data['rows']['labels'][$name] = $name;
                if (isset($data['data'][$name][$index])) {
                    $data['rows']['data'][$index][$name]['label'] = $data['data'][$name][$index]['label'];
                    $data['rows']['data'][$index][$name]['value'] = $data['data'][$name][$index]['value'];
                } else {
                    $data['rows']['data'][$index][$name]['label'] = $label;
                    $data['rows']['data'][$index][$name]['value'] = 0;
                }
                if (isset($data['data'][$name][$index])) {
                    if (null === $data['min']) {
                        $data['min'] = $data['data'][$name][$index]['value'];
                    }
                    $data['min'] = $data['min'] > $data['data'][$name][$index]['value'] ? $data['data'][$name][$index]['value'] : $data['min'];
                    $data['max'] = $data['max'] < $data['data'][$name][$index]['value'] ? $data['data'][$name][$index]['value'] : $data['max'];
                }
            }
        }
        foreach ($data['data'] as $name => $value) {
            ksort($data['data'][$name]);
        }
    }

    public function processResultsToData($type, $dataType, $colors, $result, &$data, $shift = true)
    {
        $format = $this->getFormatFromType($type);
        if (empty($data)) {
            $data['labels'] = [];
            $data['data'] = [];
            $data['colors'] = $colors;
        }
        foreach ($result as $i => $row) {
            $index = $i;
            $label = $i;
            $name = array_shift($row) . (!$shift ? $this->queryCount : null);
            $startTime = array_shift($row);
            $endTime = array_shift($row);
            if ($shift) {
                $index = date($format['index'], $startTime);
                $label = date($format['from'], $startTime) . date($format['to'], $endTime);
            }
            $data['labels'][$index] = $label;
            $data['data'][$name][$index]['label'] = date($format['from'], $startTime) . date($format['to'], $endTime);
            $data['data'][$name][$index]['value'] = $this->getValueFromDataType($row, $dataType);
        }
        $this->queryCount++;
    }

    public function getValueFromDataType(&$row, $dataType)
    {
        $value = 0;
        $count = 1;
        if ('diff' == $dataType || 'co2' == $dataType) {
            $kwh = array_shift($row);
            return 'diff' == $dataType ? $kwh : $kwh * $this->getEmissionFactor();
        } else {
            foreach ($row as $val) {
                if ($val > 0) {
                    $count++;
                    $value += $val;
                }
            }
            return $value / $count;
        }
        return 0;
    }

    public function getFormatFromType($type)
    {
        switch ($type) {
            case 'hr':
                return [
                    'index' => 'Y-m-dTH:i',
                    'from' => 'M d h:iA',
                    'to' => '-M d h:iA'
                ];
            case 'dy':
                return [
                    'index' => 'Y-m-d',
                    'from' => 'M d,',
                    'to' => ' Y'
                ];
            case 'wk':
                return [
                    'index' => 'Y-m-d',
                    'from' => 'M d',
                    'to' => '-M d, Y'
                ];
            case 'mo':
                return [
                    'index' => 'Y-m',
                    'from' => 'M d',
                    'to' => '-M d, Y'
                ];
        }
    }

    public function getQueryByGranularity($granularity, $params, $i)
    {
        $query = new Query();
        $query
            ->select($this->getColumnsByDataType($granularity, $params['data']))
            ->from($granularity)
            ->where($granularity . '.id = :id AND start_timestamp >= :min AND start_timestamp <= :max AND report = :report', [
                ':id' => $params['id'][$i],
                ':min' => strtotime($params['min_time'][$i].':00+08:00'),
                ':max' => strtotime($params['max_time'][$i].':59+08:00'),
                ':report' => $params['type']
            ])
            ->groupBy($this->getGroupByType($params['type']))
            ->orderBy('start_timestamp')
        ;
        if (self::GRANULARITY_GROUP === $granularity) {
            $query->join('INNER JOIN', 'group_meter', 'group_meter.group_id = groups.id')
                ->join('INNER JOIN', 'meter', 'meter.id = group_meter.meter_id')
            ;
        }
        $query->join('LEFT JOIN', 'meter_summary', 'meter_summary.meter_id = meter.id');
        return $query;
    }

    public function getColumnsByDataType($granularity, $dataType)
    {
        switch ($dataType) {
            case 'diff':
            case 'co2':
                return [$granularity . '.name', 'MIN(start_timestamp)', 'MAX(end_timestamp)', 'SUM(kWh_Tot_Diff)'];
            case 'avg':
                return [$granularity . '.name', 'MIN(start_timestamp)', 'MAX(end_timestamp)', 'AVG(RMS_Watts_Ln_1_Average)', 'AVG(RMS_Watts_Ln_2_Average)', 'AVG(RMS_Watts_Ln_3_Average)'];
            case 'volt':
                return [$granularity . '.name', 'MIN(start_timestamp)', 'MAX(end_timestamp)', 'AVG(RMS_Volts_Ln_1_Average)','AVG(RMS_Volts_Ln_2_Average)','AVG(RMS_Volts_Ln_3_Average)'];
            case 'amp':
                return [$granularity . '.name', 'MIN(start_timestamp)', 'MAX(end_timestamp)', 'AVG(Amps_Ln_1_Average)','AVG(Amps_Ln_2_Average)','AVG(Amps_Ln_3_Average)'];
        }

views/report/_chart.php
<?php
use dosamigos\chartjs\ChartJs;
$labels = [];
foreach ($data['labels'] as $value) {
    $labels[] = $value;
}
$dataSet = [];
foreach ($data['data'] as $name => $value) {
    $nokey = [];
    foreach ($value as $item) {
        $nokey[] = $item['value'];
    }
    $color = array_shift($data['colors']);
    $dataSet[] = [
        'label' => $name,
        'fill' => false,
        'backgroundColor' => $color,
        'borderColor' => $color,
        'pointBackgroundColor' => $color,
        'pointBorderColor' => $color,
        'pointHoverBackgroundColor' => $color,
        'pointHoverBorderColor' => $color,
        'data' => $nokey
    ];
}
?>
<?=  ChartJs::widget([
    'type' => 'line',
    'options' => [
        'height' => 100,
    ],
    'data' => [
        'labels' => $labels,
        'datasets' => $dataSet,
    ]
]); ?>

views/report/_form.php
<?php
/* @var $dropDownItems[] GroupsSearch */
use yii\helpers\Url;
use yii\helpers\Html;
$get = Yii::$app->request->get();
$count = isset($get['id']) ? count($get['id']) : 2;
$x = 0;
?>
<?= Html::beginForm('', 'get') ?>
    <input type="hidden" name="_csrf" value="<?=Yii::$app->request->getCsrfToken()?>" />
    <div class="row">
        <div class="form-group col-lg-3">
            <label for="type">Report Type</label>
            <select id="type" name="type" class="form-control">
                <option value="hr"<?= isset($get['type']) && $get['type'] == 'hr' ? ' selected="selected"' : null ?>>Hourly</option>
                <option value="dy"<?= isset($get['type']) && $get['type'] == 'dy' ? ' selected="selected"' : null ?>>Daily</option>
                <option value="wk"<?= isset($get['type']) && $get['type'] == 'wk' ? ' selected="selected"' : null ?>>Weekly</option>
                <option value="mo"<?= isset($get['type']) && $get['type'] == 'mo' ? ' selected="selected"' : null ?>>Monthly</option>
            </select>
        </div>
        <div class="form-group col-lg-3">
            <label for="data">Data Type</label>
            <select id="data" name="data" class="form-control">
                <option value="diff"<?= isset($get['data']) && $get['data'] == 'diff' ? ' selected="selected"' : null ?>>Total KWh Difference</option>
                <option value="co2"<?= isset($get['data']) && $get['data'] == 'co2' ? ' selected="selected"' : null ?>>Total KgCO<sub>2</sub></option>
                <option value="avg"<?= isset($get['data']) && $get['data'] == 'avg' ? ' selected="selected"' : null ?>>Average Watts</option>
                <option value="volt"<?= isset($get['data']) && $get['data'] == 'volt' ? ' selected="selected"' : null ?>>Average Volts</option>
                <option value="amp"<?= isset($get['data']) && $get['data'] == 'amp' ? ' selected="selected"' : null ?>>Average Amperes</option>
            </select>
        </div>
        <div class="form-group col-lg-2">
            <label for="shift">Shift Dates</label>
            <select id="shift" name="shift" class="form-control">
                <option value="yes"<?= isset($get['shift']) && $get['shift'] == 'yes' ? ' selected="selected"' : null ?>>Yes</option>
                <option value="no"<?= isset($get['shift']) && $get['shift'] == 'no' ? ' selected="selected"' : null ?>>No</option>
            </select>
        </div>
    </div>
    <table class="table">
        <thead>
        <tr>
            <th><?= ucfirst($granularity) ?></th><th>Start Date/Time</th><th>End Date/Time</th><th>Color</th><th></th>
        </tr>
        </thead>
        <tbody id="fields">
        <?php for ($i = 0; $i < $count; $i++) : ?>
            <?php
            if (isset($get['id'])) {
                $x = key($get['id']);
                next($get['id']);
            } else {
                $x = $i;
            }
            ?>
            <tr id="row-<?= $x ?>">
                <td class="form-group col-lg-3">
                    <select id="id-<?= $x ?>" name="id[<?= $x ?>]" class="form-control">
                        <?php foreach ($dropDownItems as $dropdownItem) : ?>
                            <option value="<?= $dropdownItem->id ?>"<?= isset($get['id'][$x]) && $get['id'][$x] == $dropdownItem->id ? ' selected="selected"' : null ?>><?= $dropdownItem->name ?></option>
                        <?php endforeach; ?>
                    </select>
                </td>
                <td class="form-group col-lg-3">
                    <input id="min_time-<?= $x ?>" name="min_time[<?= $x ?>]" type="datetime-local" class="form-control" value="<?= isset($get['min_time'][$x]) ? $get['min_time'][$x] : null ?>" />
                </td>
                <td class="form-group col-lg-3">
                    <input id="max_time-<?= $x ?>" name="max_time[<?= $x ?>]" type="datetime-local" class="form-control" value="<?= isset($get['max_time'][$x]) ? $get['max_time'][$x] : null ?>" />
                </td>
                <td class="form-group col-lg-1">
                    <input id="color-<?= $x ?>" name="color[<?= $x ?>]" type="color" class="form-control" value="<?= isset($get['color'][$x]) ? $get['color'][$x] : null ?>" />
                </td>
                <td class="form-group col-lg-1">
                    <a href="#" onclick="delete_row(<?=$x?>)" class="btn btn-default"><i class="glyphicon glyphicon-trash"></i></a>
                </td>
            </tr>
        <?php endfor; ?>
        </tbody>
        <tfoot>
        </tfoot>
    </table>
    <div class="row">
        <div class="col-lg-12">
            <a id="add_row" href="#" class="btn btn-default">Add Row</a>
            <input type="submit" name="submit" value="Create Report" class="btn btn-primary" />
            <input type="submit" name="submit" value="Download Data" class="btn btn-primary" />
        </div>
    </div>
<?= Html::endForm() ?>
<script type="text/javascript">
    var x = <?= $x + 1 ?>;
    function add_row()
    {
        var fields = '<td class="form-group col-lg-3">' +
            '    <select id="id-' + x + '" name="id[' + x + ']" class="form-control">' +
            <?php foreach ($dropDownItems as $dropdownItem) : ?>
            '            <option value="<?= $dropdownItem->id ?>"><?= $dropdownItem->name ?></option>' +
            <?php endforeach; ?>
            '    </select>' +
            '</td>' +
            '<td class="form-group col-lg-3">' +
            '    <input id="min_time-' + x + '" name="min_time[' + x + ']" type="datetime-local" class="form-control" />' +
            '</td>' +
            '<td class="form-group col-lg-3">' +
            '    <input id="max_time-' + x + '" name="max_time[' + x + ']" type="datetime-local" class="form-control" />' +
            '</td>' +
            '<td class="form-group col-lg-1">' +
            '     <input id="color-' + x + '" name="color[' + x + ']" type="color" class="form-control" />' +
            '</td>' +
            '<td class="form-group col-lg-1">' +
            '    <a href="#" onclick="delete_row(' + x + ')" class="btn btn-default"><i class="glyphicon glyphicon-trash"></i></a>' +
            '</td>';
        var row = document.createElement('tr');
        row.id = 'row-' + x;
        row.innerHTML = fields;
        document.getElementById('fields').appendChild(row);
        x++;
        return false;
    }

    function delete_row(x)
    {
        document.getElementById('row-' + x).remove();
        return false;
    }
    document.getElementById('add_row').onclick = add_row;
</script>

views/report/_table.php
<?php
use app\controllers\ReportController;
?>

<div class="row">
    <div class="col-lg-12">
        <table class="table table-hover">
            <thead>
                <th>Date/Time</th>
                <th><?= implode('</th><th>',($data['rows']['labels'])) ?></th>
            </thead>
            <tbody>
                <?php foreach ($data['labels'] as $index => $label) : ?>
                    <tr>
                        <td><?= $label ?></td>
                        <?php foreach ($data['rows']['data'][$index] as $item) : ?>
                            <td class="<?= ReportController::getHtmlClass($data['rows']['data'][$index], $item['value'], $data['min'], $data['max']) ?>">
                                <?= number_format($item['value'], 4) ?>
                                <?php switch (Yii::$app->request->get('data')) {
                                    case 'diff':
                                    case 'avg':
                                        echo 'KWh';
                                        break;
                                    case 'co2':
                                        echo 'KgCO<sub>2</sub>';
                                        break;
                                    default:
                                        echo Yii::$app->request->get('data') . 's';
                                        break;

                                }
                                echo 'no' == Yii::$app->request->get('shift') ? '<br />' . $item['label'] : null;
                                ?>
                            </td>
                        <?php endforeach; ?>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
<form method="post" class="form-inline">
    <div class="row">
        <div class="col-lg-3 form-group">
            <select id="highlight-option" name="highlight_option" class="form-control" style="width: 200px;">
                <option value="row-min">Row Lows</option>
                <option value="row-max">Row Highs</option>
                <option value="min">Lowest Value</option>
                <option value="max">Highest Value</option>
            </select>
            <input id="highlight-color" name="highlight_color" type="color" class="form-control" value="#ffbfc1" style="width: 50px;" />
        </div>
        <div class="col-lg-4">
            <input id="highlight" type="button" class="btn btn-default" value="Highlight" />
            <input id="highlight-clear" type="button" class="btn btn-default" value="Clear" />
        </div>
    </div>
</form>
<script type="text/javascript">
    document.getElementById('highlight').onclick = function () {
        var option = document.getElementById('highlight-option').value;
        meters = null;
        if ('row-min' == option) {
            meters = document.getElementsByClassName('meter-data-row-min');
        }
        if ('row-max' == option) {
            meters = document.getElementsByClassName('meter-data-row-max');
        }
        if ('min' == option) {
            meters = document.getElementsByClassName('meter-data-min');
        }
        if ('max' == option) {
            meters = document.getElementsByClassName('meter-data-max');
        }
        for (var e in meters) {
            meters[e].style.backgroundColor = document.getElementById('highlight-color').value;
        }
        return false;
    };
    document.getElementById('highlight-clear').onclick = function () {
        var meters = document.getElementsByClassName('meter-data');
        for (var e in meters) {
            meters[e].style.backgroundColor = 'transparent';
        }
        return false;
    };
</script>

views/report/index.php
<?php
use yii\helpers\Html;
/* @var $this yii\web\View */

$this->title = 'Reports';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-index">

    <div class="body-content">
        <div class="row">
            <div class="col-lg-12">
                <h1>Meter Reports</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-4">
                <h2>Compare Meters</h2>

                <p>Compare multiple meter readings based on a specified date range.</p>

                <p><?= Html::a('Create Report &raquo;', ['report/meter'], ['class' => 'btn btn-default']) ?></p>
            </div>
            <div class="col-lg-4">
                <h2>Compare Groups</h2>

                <p>Compare multiple group readings based on a specified date range.</p>

                <p><?= Html::a('Create Report &raquo;', ['report/groups'], ['class' => 'btn btn-default']) ?></p>
            </div>
        </div>
    </div>
</div>

views/report/report.php
<?php
/* @var $dropDownItems[] GroupsSearch */
use yii\helpers\Html;
$this->title = 'Reports';
$this->params['breadcrumbs'][] = ['label' => 'Reports', 'url' => ['index']];
$this->params['breadcrumbs'][] = ucfirst($granularity);
?>
<div class="row">
    <div class="col-lg-12">
        <h1>Compare by <?= ucfirst($granularity) ?></h1>
    </div>
</div>
<?=$this->render('_form', ['dropDownItems' => $dropDownItems, 'granularity' => $granularity]) ?>
<?php if (Yii::$app->request->get('id')) : ?>
    <?=$this->render('_chart', ['data' => $data]) ?>
    <?=$this->render('_table', ['data' => $data]) ?>
<?php endif; ?>